project_id = "pntujnoifxlzouoztscv"

[functions.ai-assistant]
verify_jwt = true

[functions.ai-task-parser]
verify_jwt = false

[functions.admin-quotation-report]
verify_jwt = false

[functions.ai-kpi-insights]
verify_jwt = false

[functions.receive-task-webhook]
verify_jwt = false

[functions.send-task-webhook]
verify_jwt = false

[functions.sync-to-estimator-crm]
verify_jwt = false
